
import type { User } from './types';

export const TEAM_SIZE_LIMIT = 4;

export const MOCK_USERS: User[] = [
  {
    id: 1,
    name: 'Elena Rodriguez',
    email: 'elena@fiu.edu',
    password: 'password123',
    major: 'Computer Science',
    academicYear: 'Senior',
    skills: ['Python', 'Machine Learning', 'Data Analysis', 'Flask'],
    interests: 'AI for social good, hiking, indie music.',
    projectIdea: 'An app that uses ML to identify plant diseases from photos.',
    isOpenToTeams: true,
  },
  {
    id: 2,
    name: 'Ben Carter',
    email: 'ben@fiu.edu',
    password: 'password123',
    major: 'Electrical Engineering',
    academicYear: 'Junior',
    skills: ['Arduino', 'C++', 'IoT', 'Circuit Design'],
    interests: 'Building custom hardware, robotics, playing guitar.',
    projectIdea: 'A smart home device that monitors energy consumption and suggests savings.',
    isOpenToTeams: true,
  },
  {
    id: 3,
    name: 'Aisha Khan',
    email: 'aisha@fiu.edu',
    password: 'password123',
    major: 'UX/UI Design',
    academicYear: 'Senior',
    skills: ['Figma', 'User Research', 'Prototyping', 'HTML/CSS'],
    interests: 'Creating accessible designs, digital art, learning new languages.',
    projectIdea: 'Redesigning a local non-profit\'s website to improve user engagement.',
    isOpenToTeams: false,
  },
  {
    id: 4,
    name: 'Carlos Gomez',
    email: 'carlos@fiu.edu',
    password: 'password123',
    major: 'Computer Science',
    academicYear: 'Sophomore',
    skills: ['JavaScript', 'React', 'Node.js', 'Firebase'],
    interests: 'Web3, video games, watching soccer.',
    projectIdea: 'A decentralized application for tracking personal carbon footprint.',
    isOpenToTeams: true,
  },
  {
    id: 5,
    name: 'Samantha Lee',
    email: 'samantha@fiu.edu',
    password: 'password123',
    major: 'Data Science',
    academicYear: 'Graduate',
    skills: ['R', 'Tableau', 'SQL', 'Statistics'],
    interests: 'Data visualization, cooking, running marathons.',
    projectIdea: 'An interactive dashboard visualizing city crime data to find patterns.',
    isOpenToTeams: true,
  },
  {
    id: 6,
    name: 'David Chen',
    email: 'david@fiu.edu',
    password: 'password123',
    major: 'Cybersecurity',
    academicYear: 'Junior',
    skills: ['Network Security', 'Penetration Testing', 'Python', 'Linux'],
    interests: 'Ethical hacking, CTF competitions, sci-fi movies.',
    projectIdea: 'A tool to scan smart contracts for common vulnerabilities.',
    isOpenToTeams: false,
  },
  {
      id: 7,
      name: 'Maria Garcia',
      email: 'maria@fiu.edu',
      password: 'password123',
      major: 'Software Engineering',
      academicYear: 'Senior',
      skills: ['Java', 'Spring Boot', 'AWS', 'Docker'],
      interests: 'Backend systems, cloud architecture, salsa dancing.',
      projectIdea: 'A scalable microservice backend for a food delivery startup.',
      isOpenToTeams: true,
  },
  {
      id: 8,
      name: 'Leo Petrov',
      email: 'leo@fiu.edu',
      password: 'password123',
      major: 'Computer Graphics',
      academicYear: 'Sophomore',
      skills: ['Unity', 'C#', 'Blender', 'Shader Programming'],
      interests: 'Game development, 3D modeling, virtual reality.',
      projectIdea: 'An educational VR experience that takes users on a tour of ancient Rome.',
      isOpenToTeams: true,
  }
];
